### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by masyuko0222** [masyuko0222/RindokukaiNote#12]
リソース設計

<details>

<summary>1回目</summary>

## ログイン
- OAuth機能を使って、Discordログインを実装する予定です。

|Method|Path|Description|
|:---|:---|:---|
|GET|/login|ログインページを表示。|
|GET|/auth/:provider/callback|OAuth 2.0によるログイン処理、ユーザー作成処理。|

<br>

## 輪読会一覧

|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs?page=1&per_page=20|開催中の輪読会一覧を表示。|
|GET|/(ルート)|開催中の輪読会一覧を表示。|
|GET|/reading_clubs?status=finished&page=1&per_page=20|終了している輪読会一覧を表示。|
|POST|/reading_clubs/:id/participations|任意の輪読会に参加。|
|DELETE|/reading_clubs/:id/participations/:id|参加している輪読会の参加取り消し。|

<br>

参加機能は、参加した輪読会を上部にソートするためだけのものなので、参加に関するページ(GET)はありません。

<br>

#### API
輪読会のデータは、フィヨルドブートキャンプ側でAPIを実装し、それを呼び出すことで輪読会一覧を取得する予定です。

|Method|Path|Description|
|:---|:---|:---|
|GET|/api/reading_clubs?page=1&per_page=20|全ての輪読会一覧を取得。|

```
[
  {
    id: 21
    title: 'ブルーベリー本輪読会',
    finished: false,
  },
  {
    id: 31
    title: 'りアクト！輪読会',
    finished: true,
  },
  ...
]
```

## READ ME・輪読会ノート一覧
**※イメージがつきづらいかもしれないので、ページのプロトタイプを貼り付けます。**

<br>

![image](https://github.com/user-attachments/assets/7b1c158b-e15c-4eb7-adad-667da9c6de20)

<br>

|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs/:id/overview|輪読会のREAD ME ・輪読会ノート一覧を表示。|
|GET|/reading_clubs/:id/read_me/edit|READ ME編集ページを表示。|
|PUT|/reading_clubs/:id/read_me/|READ MEを更新。|

<br>

各輪読会は、デフォルトで空文字のREAD MEを保有しているので、新規作成ページはありません。
削除機能も付けません。

<br>

## テンプレート
|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs/:id/template|輪読会ノートのテンプレートを表示。|
|GET|/reading_clubs/:id/template/edit|READ ME編集ページを表示。|
|PUT|/reading_clubs/:id/template/|テンプレートを更新。|

各輪読会は、デフォルトで空文字のテンプレートを保有しているので、新規作成ページはありません。
削除機能も付けません。

<br>

## 輪読会ノート
|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs/:id/notes/:id|任意の輪読会ノートを表示。|
|GET|/reading_clubs/:id/|任意の輪読会ノートを表示。輪読会のトップページは最新IDのノートを表示するようにする。|

輪読会ノートのフロントエンドは、ライブラリの関係でJavaScript(React)で実装する予定です。
そのためAPIを実装し、それを呼び出すことで輪読会ノートデータを取得する予定です。

|Method|Path|Description|
|:---|:---|:---|
|GET|/api/reading_clubs/:id/notes/?page=1&per_page=20|輪読会ノート一覧を取得。|
|POST|/api/reading_clubs/:id/notes|空文字のcontentを持つ輪読会ノートを新規作成。「新規ノート作成」押下で自動で作成される。|
|GET|/api/reading_clubs/:id/notes/:id|任意の輪読会ノートを取得。|
|PUT|/api/reading_clubs/:id/notes/:id|任意の輪読会ノートを更新。|
|DELETE|/api/reading_clubs/:id/notes/:id|任意の輪読会ノートを削除。|

```
[
  {
    id: 3,
    record_date: '2024-08-01'
    title: '第一章を終了！',
    content: `- 学習範囲<br>- p.19~23<br.- 参加者<br> - yamadaさん...`,
  },
  {
    id: 2,
    record_date: '2024-07-26'
    title: 'オブジェクトとは？',
    content: `- 学習範囲<br>- p.16~18<br>- 参加者<br> - yamadaさん...`,
  },
  {
    id: 1,
    record_date: '2024-07-19'
    title: '',
    content: `- 学習範囲<br>- <br.- 参加者<br> - ...`,
  },
  ...
]
```

</details>

<details>

<summary>2回目</summary>

## ログイン
- OAuth機能を使って、Discordログインを実装する予定です。

|Method|Path|Description|
|:---|:---|:---|
|GET|/login|ログインページを表示。|
|GET|/auth/:provider/callback|OAuth 2.0によるログイン処理、ユーザー作成処理。|

<br>

## 輪読会一覧

|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs?page=1&per_page=20|開催中の輪読会一覧を表示。|
|GET|/(ルート)|開催中の輪読会一覧を表示。|
|GET|/reading_clubs?status=finished&page=1&per_page=20|終了している輪読会一覧を表示。|
|POST|/reading_clubs/:id/participations|任意の輪読会に参加。|
|DELETE|/reading_clubs/:id/participations/:id|参加している輪読会の参加取り消し。|

<br>

参加機能は、参加した輪読会を上部にソートするためだけのものなので、参加に関するページ(GET)はありません。

<br>

#### API
輪読会のデータは、フィヨルドブートキャンプ側でAPIを実装し、それを呼び出すことで輪読会一覧を取得する予定です。

|Method|Path|Description|
|:---|:---|:---|
|GET|/api/reading_clubs?page=1&per_page=20|全ての輪読会一覧を取得。|

```
[
  {
    id: 21
    title: 'ブルーベリー本輪読会',
    finished: false,
  },
  {
    id: 31
    title: 'りアクト！輪読会',
    finished: true,
  },
  ...
]
```

## READ ME・輪読会ノート一覧
**※イメージがつきづらいかもしれないので、ページのプロトタイプを貼り付けます。**

<br>

![image](https://github.com/user-attachments/assets/7b1c158b-e15c-4eb7-adad-667da9c6de20)

<br>

|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs/:id/overview|輪読会のREAD ME ・輪読会ノート一覧を表示。|
|GET|/reading_clubs/:id/read_me/edit|READ ME編集ページを表示。|
|PUT|/reading_clubs/:id/read_me/|READ MEを更新。|

<br>

各輪読会は、デフォルトで空文字のREAD MEを保有しているので、新規作成ページはありません。
削除機能も付けません。

<br>

## テンプレート
|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs/:id/template|輪読会ノートのテンプレートを表示。|
|GET|/reading_clubs/:id/template/edit|テンプレート編集ページを表示。|
|PUT|/reading_clubs/:id/template/|テンプレートを更新。|

各輪読会は、デフォルトで空文字のテンプレートを保有しているので、新規作成ページはありません。
削除機能も付けません。

<br>

## 輪読会ノート
|Method|Path|Description|
|:---|:---|:---|
|GET|/reading_clubs/:id/notes/:id|任意の輪読会ノートを表示。|
|GET|/reading_clubs/:id/|任意の輪読会ノートを表示。輪読会のトップページは最新IDのノートを表示するようにする。|

輪読会ノートのフロントエンドは、ライブラリの関係でJavaScript(React)で実装する予定です。
そのためAPIを実装し、それを呼び出すことで輪読会ノートデータを取得する予定です。

|Method|Path|Description|
|:---|:---|:---|
|GET|/api/reading_clubs/:id/notes/?page=1&per_page=20|輪読会ノート一覧を取得。|
|POST|/api/notes|空文字のcontentを持つ輪読会ノートを新規作成。「新規ノート作成」押下で自動で作成される。|
|GET|/api/notes/:id|任意の輪読会ノートを取得。|
|PUT|/api/notes/:id|任意の輪読会ノートを更新。|
|DELETE|/api/notes/:id|任意の輪読会ノートを削除。|

```
[
  {
    id: 3,
    record_date: '2024-08-01'
    title: '第一章を終了！',
    content: `- 学習範囲<br>- p.19~23<br.- 参加者<br> - yamadaさん...`,
  },
  {
    id: 2,
    record_date: '2024-07-26'
    title: 'オブジェクトとは？',
    content: `- 学習範囲<br>- p.16~18<br>- 参加者<br> - yamadaさん...`,
  },
  {
    id: 1,
    record_date: '2024-07-19'
    title: '',
    content: `- 学習範囲<br>- <br.- 参加者<br> - ...`,
  },
  ...
]
```

</details>

**Comment by betachelsea** [comment]
拝見しました！ :eyes: 
特別な問題点は無いように思いましたが、別途モデルについて拝見・仕様についていくつか質問させていただいたあとに、追加コメントするかもしれませんが、一旦下記コメントです。

- [IMO] API について、当面は一括でとっても問題ないくらいのデータ量かなと思いますが、渡す側/受け取る側両面とも、ページング的処理は考慮しておいたほうが将来的には良さそうと考えます。もし取り扱ってるデータ量のせいでタイムアウトとかになったら？というのは、設計する上で考慮はしておきたいポイントですね。
- [nits] 仕様ドキュメントとして、概ね最初に `/` ( `/reading_clubs/...` )と入力いただいていますが、api関係だけ `api/reading_clubs/...` で `/` から始まらないのがちょっと気になりました。

**Comment by masyuko0222** [comment]
@betachelsea 
ありがとうございます！
ご指摘点を修正しました。現状大きな変更ではないの、直接編集する形で対応しています。

変更点は以下です。ご指摘のapi箇所に加え、輪読会一覧もページング処理を入れることにしました。

-  開催中の輪読会一覧を表示
  - GET `/reading_clubs`  ⇒ `/reading_clubs?page=1&per_page=20`
- 終了した輪読会一覧を表示
  - GET `/reading_clubs?status=finishe` ⇒ `/reading_clubs?status=finished&page=1&per_page=20`
- 輪読会ノート一覧を表示
  - GET `/api/reading_clubs/:id/notes` ⇒ `/api/reading_clubs/:id/notes/?page=1&per_page=20`

ご確認のほどよろしくお願いします！

**Comment by betachelsea** [comment]
修正ありがとうございます！ 　前回との差分が比較できない状態のため、なんとなくですが、表記内容がブラッシュアップされたように感じました ✨ 

モデルのレビューを経て見直し、改めて少しコメントします 🙏 

- 重箱の隅レベルの話ですが、下記は「テンプレート編集ページを表示」ですね。
  - > GET | /reading_clubs/:id/template/edit | READ ME編集ページを表示。
- 輪読会ノートを取得したり更新したりするとき、URLには reading_club の id と note の id のどちらともを含むようですが、ひとつの Note のデータを扱う時に実は reading_club の id  は必要ないですね。もし、「reading_club の32番がURLでは指定されているけど、note の80番に紐づいているreading_club は20番となっている」といった不整合なリクエストが飛んできた時に、どう処理するかを事前に決めておくと、実装時に悩まなくてすみそうと思いました 💡

**Comment by masyuko0222** [comment]
ありがとうございます！
ご指摘点踏まえて、
https://github.com/masyuko0222/RindokukaiNote/issues/12#issue-2463335106
に「２回目」として修正後のリソース設計を記しました。

> ひとつの Note のデータを扱う時に実は reading_club の id は必要ないです

なるほど。おっしゃる通り適切に関連付けがされていれば、reading_club側のidは不要ですね。
取り急ぎ、api含めnoteのshow, update, deleteに関してはreading_clubのidを消去してみました。

一方でユーザーに見えるURLだったり、ルーティングもreading_clubのidがある方が分かりやすいのかなぁと思いました。

修正では一旦reading_clubのidを消す形た対応しましたが、URLはそのままで、不正なURLを打たれたらエラー画面を出すなどのような対応にした方が良いかなとも思っています。

**Comment by betachelsea** [comment]
> 一方で、ユーザーに見えるURLはreading_clubのidを含んでいた方がユーザーライクなのかなぁと考えています。

そうですね！同意です :+1: 

> ユーザーが見えるURLのみreading_club/:idを付け、apiに関してはなくす。

こちらも良いと思います！ Rails でいう shallow オプションにかなり近い様子だなと思いました。
こちらのドキュメントが実装時の参考になりそうです →  [Rails のルーティング - Railsガイド - 2.7.2 浅いネスト](https://railsguides.jp/routing.html#%E6%B5%85%E3%81%84%E3%83%8D%E3%82%B9%E3%83%88)

> `POST	/api/notes` 

こちらについては、どの輪読会の note か、という情報を与えなくてはなりませんが、URLになくても、リクエストに含めれば良いので問題無いと思います。もしくは上記の "浅いネスト" を使おうとすると、ちょっと変わってくるかもしれませんが、特別問題視する点ではないと思っています  :ok_man: 


リソース設計についてはLGTMとしたいと思います！ :+1:

**Comment by masyuko0222** [comment]
すみません、浅いネストについて質問なのですが、以下のパスも浅いネストのしてもいいのかな？と思いました。

- `DELETE /reading_clubs/:id/participants/:id`

⇒ `DELETE /participants/:id`に変更？

パスhelperを使うとき、不要な`reading_club_id`も渡さないといけないのがやや冗長かなと思ったのが理由です。
`link_to reading_club_participants_path(reading_club, participant)...`


一方で`routes.rb`でDELETE時のみ分けて書くと可読性が落ちてしまうのかなとも悩んでいます。
```ruby
# routes.rb変更前
resources :reading_clubs, only: [:index] do
  resources :participants, only: [:create, :destroy], controller: 'reading_clubs/participants'
end
```
```ruby
# routes.rb変更後
resources :reading_clubs, only: [:index] do
  resources :participants, only: [:create], controller: 'reading_clubs/participants'
end

resources :participants, only: [:destroy]
```

どちらが良いなどご意見あったらお聞きしたいですm(__)m
