### ISSUE TITLE
データ設計

### ISSUE THREAD

**Issue by masyuko0222** [masyuko0222/RindokukaiNote#13]
![image](https://github.com/user-attachments/assets/ea26c8cd-7ba4-433a-8309-e8c166068d5f)

users 1 - * participants * - 1 reading_clubs
reading_clubs 1 - 1 templates
reading_clubs 1 - 1 readmes
reading_clubs 1- * notes

**Comment by betachelsea** [comment]
拝見しました！ 

## 相談事項

ReadMe と Template は、このテーブル設計とペーパープロトタイプより、1つの輪読会情報につき1個ずつのようですね。複数テーブルでそれぞれ必ず1レコードを保持し続ける仕様は、簡単そうにみえて、意外とどこかうっかり強制的・例外的にレコードを作ってしまったりすると後々面倒なことになりがちです。0 or 1 でもなく、必ず1つのデータが必要なのであれば、1テーブルにまとめることをオススメしたいです。更新を別にしたいということであれば、ちょっと調整は必要ですが、URLは分けるけど同じレコードに対して更新をかける、ということも可能です。こちらの件、改めてご検討お願いいたします！ :pray:


## 細かいこと
- データ型のstringは、比較的短い文字数を入れる想定の時に使います。(255文字くらいかな…すみません、ちょっと公式ドキュメントからサッと参照先を拾えませんでしたが…)ReadMe と Template の中身にはもっとたくさんの文字列を入れることが求められそうな気がするので、text 扱いが良いかなと思いました。Noteについても同様そうですね。
- Notesテーブルの `record_date` は日付のみ入れるのですね。日付のカラムの命名は、よく `〇〇_on` とすることが多いのでおすすめしたいです。 [Rails: 日付や時刻のカラム名を命名規則に合わせよう（翻訳）｜TechRacho by BPS株式会社](https://techracho.bpsinc.jp/hachi8833/2017_11_01/47310)
  - また、Notesテーブルは1輪読会にたいしてたくさん発生するデータなので、並び替えを何に頼るかというところはちょっと気になりました。Railsで作る場合は、たいていcreated_at というカラムが生えがちなので、それを使っても良いですが、もし並び替えに使うために `record_date` を使う予定であれば、万一、同一日に 2件のファイルができた時に備えて、内部的にはdatetimeで扱っておくと良さそうと思いました。(日時を扱う場合は `〇〇_at` というカラム名がよく使われます) 
  
## 他の感想
  - DiscordのOAuth2のログイン認証が入りそうですね。もしかすると認証情報を保存するためのテーブルが必要かもと思いますが、多分おまかせできるGemがあると思うので、ER図にはなくても大丈夫だと考えました。
  - ノートは複数人で同時編集するイメージなんですね！自分も実装したことがないのですが、いま・誰が・どの行を・どのように 編集しているのか、という情報を何かしらサーバーとやり取りが必要なのではと思いました。その情報をどうやりとりするかというのは、もしかしたらDBとは別なのかもしれませんが、データ管理という意味では実装する前に一息ついて考えるべきトピックかもしれません。頭の片隅にでもおいていただけると良さそうなので、補足まで〜 :pray:

**Comment by masyuko0222** [comment]
@betachelsea 
ありがとうございます！
何点か質問＆回答させてください。

## 相談事項について
１つのテーブルにすることで、「TemplateだけReadingClubと紐づいているレコードがあるが、ReadMeには存在しない」のような整合性がないデータ状況を避けられる、ということだと思いました！
確かに、１テーブルにまとめて、外部キーであるReadingClubIdにunique制約を持たせたら管理も楽になりそうです。

> 意外とどこかうっかり強制的・例外的にレコードを作ってしまったりする

ただこうなるシチュエーションがちょっと思いつかなかったのですが、もし具体的なシチュエーションがあったら教えていただきたいです・・・！

## 細かいことについて
#### stringとtextについて
すみませんこちらは横着してデータ型を記入してしまっていました。
ご指摘の通りtext型で入力したいと思います。

#### record_dateについて
今回はユーザーは任意の日付のみの入力で、時刻は入力しない形としています。
「任意の日付」の通り、この日付は好きに変えられます(デフォルトでは新規作成した日付)。

そのため、今回は
- record_on：入力した任意の日付をDate型で保存。

にし、sort用の時刻はこの日付に加えて、created_atの時刻部分を取り出して利用しようかなと考えています。

この`record_on`について、時刻を保持しないためDateTimeよりDateで保有するべきだと思ったのですがいかがでしょうか？

## 他の感想について
#### 認証情報保存用のテーブルについて
Discord認証はまだ認証→ログインのところまでしか技術検証をしていなかったので、認証を保存しておくテーブルのことは抜けていました！また調査したいと思います。

ちなみにセッションでアクセストークンとかを保存しておいたら、再ログインの手間を省けるのかなと浅く考えていたのですが、セッションはスコープが広いので出来るだけ利用を避けるべきなんでしょうか？

#### 共同編集のリアルタイム状況について
JSライブラリの、`Y.js`を利用すると良い感じにやってくれます。
ただいい感じにやってくれることの検証までは済んだのですが、内部でどうやっているのか・データの流れまでは追えていない状況です 💦
ここはもう少し掘るべきだと思っているので、ご指摘の通りもう少し調査できたらと思います・・・！

**Comment by masyuko0222** [comment]
@betachelsea 
![Uploading 240826203840792.JPG…]()

**Comment by masyuko0222** [comment]
@betachelsea 
![240826203840792](https://github.com/user-attachments/assets/ac57d6db-278a-41f6-bed2-bf72d898ea70)

**Comment by betachelsea** [comment]
@masyuko0222  質問ありがとうございます！

## readmeとtemplateを１つのテーブルにすることについて
はい、「整合性がないデータ状況を避けられる」と解釈いただいてOKです！
また、他に利点を挙げるとすれば、「データを呼び出すときに他のテーブルを参照しに行く処理コストが減る」、という点もちょっとですが言えるかなと思いました。

## record_dateについて

> ご指摘を受け、record_onのような命名にしようかと思います。

1点命名ルールについて補足させてください！
Railsでよく見られる命名ルールとして、日付・時刻系を扱う場合、`過去形_on` 、`過去形_at` という表現になるケースが多いです。例えば Rails が用意している migration での `timestamps`  マクロは、`created_at` ・ `updated_at` というカラムを作ります。なので、 `recorded_on` と言う表現が一番しっくりきそうです。

[Active Record マイグレーション - Railsガイド](https://railsguides.jp/active_record_migrations.html)

> このrecord_onについて、時刻を保持しないためdatetimeよりdateで保有しても問題ないでしょうか？
> 組み合わせて降順ソートで表示できるようにしたいと思っています。

お〜なるほど！ 日付でグルーピングして、そのなかの更新日時順にしたいということですね。グルーピング目的であえてdateにする、ということであればOKだとおもいます :+1:

## 認証情報保存用のテーブルについて

> この認証情報の保存というのは、キャッシュ的な役割で、２回目以降のログインを省略するなどして利便性を上げることが目的になるのでしょうか？

自分のコメント時の想定としては、例えばdeviseを入れようと思ったら自動的に色々生やされるカラムのことを考えて書いたものでした。すみません、改めて読むと「テーブル」ではなく「カラム」と書くべきでした！ 🙇   また、今回書いていただいたコメントを鑑みるに、メールアドレス/パスワードやパスワード再発行などのdevise的機能は導入しない方針、というように解釈しました。それであれば、セッション周りの実装は自力でする必要はありそうですが、OmniAuthのみ利用して uid, provider のみテーブルに保存する、という方向でできそうですね。いいと思いました〜 :ok_man: 

## 画像のER図について

- OmniAuth のみの構成でも、Usersテーブルに uid カラムは必要そうです。
- 長そうな文字列が入るカラムはtext型になっていていいですね！ :+1:
- 【こちら再ご確認お願いします！】readmeとtemplateについて、自分のイメージでは `ReadingClubs` テーブルに完全に合併吸収される想定をしておりました！ あまりこの2カラムを別テーブルに分けるメリットは無さそうだと思います。中身がない、ということは NULL かどうか、といったところで判断で良いと考えます。いかがでしょう？

**Comment by masyuko0222** [comment]
## recorded_onについて
過去形の旨承知いたしました！確かに`created_at`や`updated_at`は過去形であることを見逃していました。

> お〜なるほど！ 日付でグルーピングして、そのなかの更新日時順にしたいということですね。グルーピング目的であえてdateにする、ということであればOKだとおもいます

こちらについて、町田さんと相談したところ「検索機能も付くし、日付(月)ごとにグルーピングしなくてもよいのでは？」という話になりました。
なので、今回はグルーピングをせずに単に日付(+時刻)でソートをするだけになる予定です。

またrecorded_onが日付だけで時刻がない理由は、輪読会の記録としては日付のみがあれば十分だと考え、時刻を入力する手間を省いた方が利便性が上がるかなと思った次第です。

**Comment by betachelsea** [comment]
> 再修正いたしました！


ありがとうございます！ かなりスッキリしたER図になりましたね :+1: 

## date型について

なるほど、これは輪読会の実施日という意味合いだったのですね！ 後日にNoteを作る、ということもありえるので、作成日/更新日とは別にdate型を準備する、と解釈しました。たしかにそれだとdate型が適切ですね。

今回、カラム名が `recorded_on` だったので、 "(Noteを)記録した日" という意味合いなのかな、と思った→ それなら created_at と事実上同じではないか？ 保存したタイミングの日時を自動的に保持すればよいのでは？ と考えてしまっておりました。ペーパープロトタイプを見直しにいったところ、ちゃんと日付を選べるUIがありましたね！ 失礼しました :bow: 
カラム名について、recorded だと その Note を記録(書いた)時、という印象が個人的には強くあります。こちら、命名再検討の余地はありますでしょうか？ 
よく考えたら、そもそもこれが何を示すのかをはっきり伺っていなかったかもですね…! :bow: 「開催日」とか「実施日」という認識でよいでしょうか？

ちなみに末尾の命名は、暗黙的に

- `*_on` → date型
- `*_at` → datetime型

なので、今回の場合は `*_on` で良いと思います :+1:

**Comment by masyuko0222** [comment]
@betachelsea 
再修正しました！
![image](https://github.com/user-attachments/assets/53d841c2-0267-47a2-b35b-675dafe922f0)

> カラム名について、recorded だと その Note を記録(書いた)時、という印象が個人的には強くあります。こちら、命名再検討の余地はありますでしょうか？

仰る通りで、説明不足&微妙な命名で誤解させてしまいすみませんでした🙇

「開催日」の方を採用し、`held_on`という命名にさせていただきました。

**Comment by betachelsea** [comment]
@masyuko0222 修正ありがとうございました！ 

あ、重箱の隅ですが、Notes テーブルの `content` は長いテキストが入ると思うので、`text` 型でお願いします 🙏 

LGTMとします〜！ 👍
